### ISSUE TITLE
Unknown issue when import library Nekoton

### ISSUE THREAD

**Issue by longdoan479** [broxus/nekoton-python#2]
Hello, im running the example code, but when i import this library, it show error like the image, how can i fix it?
![image](https://github.com/broxus/nekoton-python/assets/55242514/4bb9459f-ac52-45c8-9abc-b7d6f5817cc3)

Thanks for help me!!!

**Comment by Rexagon** [comment]
It seems like you are using an old python version. These bindings require python 3.10+
