### ISSUE TITLE
Add __hash__ and __eq__ methods to Address to use it as a dict keys

### ISSUE THREAD

**Issue by 30mb1** [broxus/nekoton-python#9]

**Comment by Rexagon** [comment]
`Address` already implements this - https://github.com/broxus/nekoton-python/blob/master/src/models.rs#L1306-L1312

**Comment by 30mb1** [comment]
Looks like it doesnt work 
![image](https://github.com/broxus/nekoton-python/assets/15921290/1173e387-2cb3-42bf-8c86-3d5f5145002f)

**Comment by Rexagon** [comment]
Done
